### PR TITLE
Refactor & Use of Docstrings

### PR DESCRIPTION
**Pull request by maplepy**
As explained in my issue #2  you didn't use the docstrings correctly. You can now merge my repo with yours so pmtw uses documentation. Note, there are still a lot of problems with your docstrings, a bunch of those have unfinished sentences or are cutting midway through those. Parameters are missing on almost every docstrings and some documentation is very unclear as of what it does.

Hope you'll be able to do something on that since your project seems very nice but the lack of documentation makes the module very annoying and frustrating to use

### CODE REVIEW

**Comment by maplepy** [comment]
Note that I also removed unused imports

**Comment by adhesivecheese** [comment]
So it looks like a large chunk of this pull request is converting tabs to spaces, which makes evaluating your actual changes difficult. Usage of Tabs for indentation is not mandated by PEP8, merely recommended - and I am firmly of the belief it's a braindead recommendation. Please convert the spaces for indentation back to tabs, and I'll be happy to take a look again!

**Comment by maplepy** [comment]
> Usage of Tabs for indentation is not mandated by PEP8, merely recommended 

I had to do that to get the proper indentation, otherwise I had a ton of errors saying indentation was inconsistent

If you know how I can edit the pr please tell me and I'll see what I can do

**Comment by maplepy** [comment]
Sadly don't have much time these days so I don't think I'll be able to redo it but I highly recommend you to use proper docstrings when creating such a project, it should look like that when done correctly:

``` python
def whateverfunction(passed, arguments):
    '''
    Get Index of a specific moderator in the list, adds mod to the list if he isn't
            there already

    Parameters
    ----------
    red : Reddit
        Reddit instance (praw) that we will be using to access the wiki
    sub : str
        Name of the subreddit to fetch the mod index from
    mod : str
        Name of the moderator who's index we are fetching

    Returns
    -------
    int
        Index of the moderator in the list
    ''' 
```

not like whatever this is in pmtw/settings.py:

```python
	"""
	Returns usernote colors as a list. Use get_banMacros(local="False")
	to fetch reasons from Reddit before returning.
	"""
	@localdata
	def get_banMacros(self):
```

**Pull request closed without merging**
